### ISSUE TITLE
블로그 Post 폰트 크기 조절이 필요합니다.

### ISSUE THREAD

**Issue by JunhwanPark** [nerdnerdoo/nerdnerdoo.github.io#2]
블로그 Post 폰트 크기가 너무 커서 PC 에서 볼때 부담스럽네요... :)
모바일은 그래도 괜찮은것 같구요.

**Comment by webispy** [comment]
Base 폰트 크기가 화면 크기마다 다르게 설정되어 있는데, 모두 16으로 고정시켰습니다. :)
